version: '3.8'


services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - ./certbot-data/www/:/var/www/certbot/:ro
      - ./certbot-data/conf/:/etc/nginx/ssl/:ro
    networks:
      - shared_network
  
  certbot:
    image: certbot/certbot:latest
    env_file:
      - .env
    volumes:
      - ./certbot-data/www/:/var/www/certbot/:rw
      - ./certbot-data/conf/:/etc/letsencrypt/:rw

networks:
  shared_network:
    external: true
